### ISSUE TITLE
OSCAL Literature Resources

### ISSUE THREAD

**Issue by idmken** [actiac-ato-as-code/aac-techdata#1]
A task to create a running list of OSCAL literature resources.

**Comment by idmken** [comment]
https://software.af.mil/training/ - Not specific to OSCAL
https://github.com/oscal-club/awesome-oscal
https://www.fedramp.gov/using-the-fedramp-oscal-resources-and-templates/
https://github.com/GSA/fedramp-automation
https://pages.nist.gov/OSCAL/

**Comment by xee5ch** [comment]
Al from OSCAL Club here. Perhaps we can get a sense of what questions we want answered about OSCAL or security automation we want answered, and then structure links and references to that?

**Comment by idmken** [comment]
Consolidated.
