### ISSUE TITLE
First pages...

### ISSUE THREAD

**Issue by Yodemite** [actiac-ato-as-code/aac-techdata#3]
[ATOasCODE v.1.docx](https://github.com/actiac-ato-as-code/aac-techdata/files/12052125/ATOasCODE.v.1.docx)

**Comment by xee5ch** [comment]
If we are in this work group are we expected to read this and provide feedback or was this already decided upon by those who attended the last sync?

**Comment by Yodemite** [comment]
This work group can decide what they choose to do with this contribution - nothing was decided by the group other than to contribute - and no feedback is requested. This contribution may add context to the data tools and methodology the group will develop/propose for the white paper. Now that I have wrapped my head around what may be the scope of expectations, we can hash out any misunderstanding now (or at the next meeting) and not start debating mid-September.

**Comment by idmken** [comment]
Consolidated.
